# HerbaScope API image. Build context: repository root (see docker-compose.yml).
# Model artifacts and data are mounted at runtime, not baked in: they are regenerated by the
# pipeline and the Mikrobat images must not be redistributed inside an image.
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# libgomp1: OpenMP runtime required by faiss-cpu and torch on slim images.
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
# CPU-only torch wheel first: the default Linux wheel pulls multi-GB CUDA libraries.
RUN pip install torch==2.14.0 --index-url https://download.pytorch.org/whl/cpu \
    && pip install -r requirements.txt

COPY ml ./ml
COPY services/api ./services/api

RUN useradd --create-home --uid 10001 herbascope \
    && mkdir -p /app/data /app/models \
    && chown herbascope /app/data
USER herbascope

EXPOSE 8000
HEALTHCHECK --interval=15s --timeout=5s --start-period=60s --retries=5 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/api/v1/health', timeout=4)"

CMD ["python", "-m", "uvicorn", "app.main:app", "--app-dir", "services/api", "--host", "0.0.0.0", "--port", "8000"]
