"""Pick the three presentation cases from real evaluation images (never synthetic).

  strong_evidence       Mikrobat test image, PRELIMINARY_PASS, correct class, highest evidence strength
  conflicting_evidence  Mikrobat test/held-out image, REVIEW_REQUIRED with LOW agreement
                        (classifier and retrieval favour different classes), highest classifier confidence
  unknown               DIMPSAR evaluation image, UNKNOWN, lowest top reference similarity

A case is reported as unavailable when no evaluated image satisfies its definition.

Outputs: data/demo/<case>.png, data/demo/demo_cases.json, docs/reports/demo_cases.md
Usage:   python -m scripts.prepare_demo_cases   (after `python -m ml.evaluation.evaluate`)
"""

from __future__ import annotations

import json
import shutil
import sys

import pandas as pd

from ml import paths
from ml.training import datasets as ds

DEMO_DIR = paths.DATA_DIR / "demo"

CASES = {
    "strong_evidence": {
        "expected_decision": "PRELIMINARY_PASS",
        "select": lambda f: f[
            (f["split"] == ds.TEST)
            & (f["decision"] == "PRELIMINARY_PASS")
            & (f["predicted_class"] == f["true_class"])
        ].sort_values("strength", ascending=False),
    },
    "conflicting_evidence": {
        "expected_decision": "REVIEW_REQUIRED",
        "select": lambda f: f[
            f["split"].isin([ds.TEST, ds.HELDOUT_KNOWN])
            & (f["decision"] == "REVIEW_REQUIRED")
            & (f["agreement"] == "LOW")
        ].sort_values("confidence", ascending=False),
    },
    "unknown": {
        "expected_decision": "UNKNOWN",
        "select": lambda f: f[(f["split"] == ds.OOD_EVALUATION) & (f["decision"] == "UNKNOWN")].sort_values(
            "top_similarity"
        ),
    },
}


def main() -> int:
    samples_path = paths.MODEL_REPORTS_DIR / "evaluation_samples.csv"
    if not samples_path.is_file():
        raise FileNotFoundError("Run `python -m ml.evaluation.evaluate` first.")
    samples = pd.read_csv(samples_path, keep_default_na=False)
    if DEMO_DIR.exists():
        shutil.rmtree(DEMO_DIR)
    DEMO_DIR.mkdir(parents=True)
    cases = {}
    for name, definition in CASES.items():
        candidates = definition["select"](samples)
        if candidates.empty:
            cases[name] = {"available": False, "expected_decision": definition["expected_decision"]}
            continue
        row = candidates.iloc[0]
        target = DEMO_DIR / f"{name}.png"
        shutil.copyfile(paths.DATA_DIR / row["path"], target)
        cases[name] = {
            "available": True,
            "file": target.relative_to(paths.REPO_ROOT).as_posix(),
            "source_path": row["path"],
            "split": row["split"],
            "dataset": row["dataset"],
            "true_class": row["true_class"],
            "fragment_type": row["fragment_type"],
            "expected_decision": definition["expected_decision"],
            "evaluated": {
                key: row[key]
                for key in (
                    "predicted_class",
                    "confidence",
                    "retrieved_class",
                    "top_similarity",
                    "agreement",
                    "unknown_status",
                    "unknown_risk",
                    "decision",
                )
            },
        }
    (DEMO_DIR / "demo_cases.json").write_text(json.dumps(cases, indent=2, default=float), encoding="utf-8")
    lines = [
        "# Demo Cases",
        "",
        "_Generated by `python -m scripts.prepare_demo_cases` from `models/reports/evaluation_samples.csv`. "
        "Do not edit by hand._",
        "",
        "Upload these files from `data/demo/` on the Analyze page. Each is a real evaluation image; the values below "
        "are what the evaluated pipeline produced.",
        "",
        "| Case | File | Source | Truth | Prediction (confidence) | Retrieved | Top similarity | Agreement | Unknown | Decision |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name, case in cases.items():
        if not case["available"]:
            lines.append(f"| {name} | unavailable | no evaluated image satisfies this case | | | | | | | |")
            continue
        e = case["evaluated"]
        lines.append(
            f"| {name} | `{case['file']}` | {case['dataset']} / {case['split']} | {case['true_class']} | "
            f"{e['predicted_class']} ({float(e['confidence']):.1%}) | {e['retrieved_class']} | "
            f"{float(e['top_similarity']):.3f} | {e['agreement']} | {e['unknown_status']} | **{e['decision']}** |"
        )
    paths.DOCS_REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    (paths.DOCS_REPORTS_DIR / "demo_cases.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {name: case.get("evaluated", {}).get("decision", "unavailable") for name, case in cases.items()},
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
